---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update Repositories
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - include_tasks: packages.yml
    - include_tasks: unattended-upgrades.yml

  handlers:
    - name: Restart unattended-upgrades
      systemd:
        name: unattended-upgrades
        state: restarted
